import type { Definition } from "@bnto/registry";

/** Simple flat definition: input → compress → output. */
export const SIMPLE_DEF: Definition = {
  id: "root",
  type: "group",
  version: "1.0.0",
  name: "Test",
  position: { x: 0, y: 0 },
  metadata: {},
  parameters: {},
  inputPorts: [],
  outputPorts: [],
  nodes: [
    {
      id: "input",
      type: "input",
      version: "1.0.0",
      name: "Input",
      position: { x: 0, y: 0 },
      metadata: {},
      parameters: { mode: "file-upload" },
      inputPorts: [],
      outputPorts: [{ id: "out-1", name: "files" }],
    },
    {
      id: "compress",
      type: "image-compress",
      version: "1.0.0",
      name: "Compress",
      position: { x: 200, y: 0 },
      metadata: {},
      parameters: { quality: 80 },
      inputPorts: [{ id: "in-1", name: "files" }],
      outputPorts: [{ id: "out-1", name: "files" }],
    },
    {
      id: "output",
      type: "output",
      version: "1.0.0",
      name: "Output",
      position: { x: 400, y: 0 },
      metadata: {},
      parameters: { mode: "download" },
      inputPorts: [{ id: "in-1", name: "files" }],
      outputPorts: [],
    },
  ],
};

/** Nested definition with containers: input → group(loop(rename)) → output. */
export const NESTED_DEF: Definition = {
  id: "root",
  type: "group",
  version: "1.0.0",
  name: "Rename Files",
  position: { x: 0, y: 0 },
  metadata: {},
  parameters: {},
  inputPorts: [],
  outputPorts: [],
  nodes: [
    {
      id: "input",
      type: "input",
      version: "1.0.0",
      name: "Input",
      position: { x: 0, y: 0 },
      metadata: {},
      parameters: {},
      inputPorts: [],
      outputPorts: [],
    },
    {
      id: "batch-rename",
      type: "group",
      version: "1.0.0",
      name: "Batch Rename",
      position: { x: 200, y: 0 },
      metadata: {},
      parameters: {},
      inputPorts: [],
      outputPorts: [],
      nodes: [
        {
          id: "rename-loop",
          type: "loop",
          version: "1.0.0",
          name: "Loop",
          position: { x: 0, y: 0 },
          metadata: {},
          parameters: { mode: "forEach" },
          inputPorts: [],
          outputPorts: [],
          nodes: [
            {
              id: "rename-file",
              type: "file-rename",
              version: "1.0.0",
              name: "Rename File",
              position: { x: 0, y: 0 },
              metadata: {},
              parameters: { prefix: "default-" },
              inputPorts: [],
              outputPorts: [],
            },
          ],
        },
      ],
    },
    {
      id: "output",
      type: "output",
      version: "1.0.0",
      name: "Output",
      position: { x: 400, y: 0 },
      metadata: {},
      parameters: {},
      inputPorts: [],
      outputPorts: [],
    },
  ],
};

/** Multi-node definition: resize + compress (two leaf processors). */
export const MULTI_NODE_DEF: Definition = {
  id: "root",
  type: "group",
  version: "1.0.0",
  name: "Multi-Node",
  position: { x: 0, y: 0 },
  metadata: {},
  parameters: {},
  inputPorts: [],
  outputPorts: [],
  nodes: [
    {
      id: "input",
      type: "input",
      version: "1.0.0",
      name: "Input",
      position: { x: 0, y: 0 },
      metadata: {},
      parameters: {},
      inputPorts: [],
      outputPorts: [],
    },
    {
      id: "resize",
      type: "image-resize",
      version: "1.0.0",
      name: "Resize",
      position: { x: 200, y: 0 },
      metadata: {},
      parameters: { width: 1200 },
      inputPorts: [],
      outputPorts: [],
    },
    {
      id: "compress",
      type: "image-compress",
      version: "1.0.0",
      name: "Compress",
      position: { x: 400, y: 0 },
      metadata: {},
      parameters: { quality: 80 },
      inputPorts: [],
      outputPorts: [],
    },
    {
      id: "output",
      type: "output",
      version: "1.0.0",
      name: "Output",
      position: { x: 600, y: 0 },
      metadata: {},
      parameters: {},
      inputPorts: [],
      outputPorts: [],
    },
  ],
};
