/**
 * Codegen: engine catalog → TypeScript modules.
 *
 * Reads `engine/catalog.snapshot.json` (generated by the Rust engine)
 * and produces:
 *   - `src/generated/catalog.ts` — node type definitions + processor metadata
 *   - `src/generated/schemas.ts` — Zod schemas for engine-backed node types
 *   - `src/generated/definitionSchema.ts` — JSON Schema for `.bnto.json` files
 *
 * The Rust engine is the single source of truth for ALL node metadata.
 * Run via: `task nodes:generate` or `npx tsx scripts/generate-from-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";

// --- Paths ---

const ROOT = resolve(dirname(import.meta.url.replace("file://", "")), "../../../..");
const CATALOG_PATH = resolve(ROOT, "engine/catalog.snapshot.json");
const GENERATED_DIR = resolve(ROOT, "packages/@bnto/nodes/src/generated");
const CATALOG_OUTPUT = resolve(GENERATED_DIR, "catalog.ts");
const SCHEMAS_OUTPUT = resolve(GENERATED_DIR, "schemas.ts");
const DEF_SCHEMA_OUTPUT = resolve(GENERATED_DIR, "definitionSchema.ts");
const DOCS_DIR = resolve(ROOT, "packages/@bnto/nodes/docs");

// Clean up old separate nodeTypes.ts if it exists
const OLD_NODE_TYPES = resolve(GENERATED_DIR, "nodeTypes.ts");

// --- Types matching engine/catalog.snapshot.json schema ---

interface CatalogEnvelope {
  version: string;
  nodeTypes: RawNodeType[];
  processors: RawProcessor[];
  definitionSchema?: Record<string, unknown>;
}

interface RawNodeType {
  name: string;
  label: string;
  description: string;
  category: string;
  isContainer: boolean;
  platforms: string[];
  icon: string;
}

interface RawProcessor {
  nodeType: string;
  operation: string;
  name: string;
  description: string;
  category: string;
  accepts: string[];
  platforms: string[];
  parameters: RawParameter[];
}

interface ParamConditionEntry {
  param: string;
  equals: string;
}

interface RawParameter {
  name: string;
  label: string;
  description: string;
  paramType: { type: string; options?: string[] };
  default?: unknown;
  constraints?: { min?: number; max?: number; required?: boolean };
  placeholder?: string;
  hidden?: boolean;
  visibleWhen?: ParamConditionEntry | ParamConditionEntry[];
  requiredWhen?: ParamConditionEntry | ParamConditionEntry[];
  surfaceable?: boolean;
}

// --- Read catalog ---

const raw = readFileSync(CATALOG_PATH, "utf-8");
const catalog: CatalogEnvelope = JSON.parse(raw);

// --- Helpers ---

function indent(s: string, n: number): string {
  const pad = "  ".repeat(n);
  return s
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}

function serializeValue(v: unknown): string {
  if (v === null || v === undefined) return "undefined";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}

/** Convert kebab-case to camelCase. */
function toCamelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

/** Convert kebab-case to PascalCase. */
function toPascalCase(s: string): string {
  const camel = toCamelCase(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

/** Serialize a ParamCondition to TypeScript code. */
function serializeCondition(cond: ParamConditionEntry | ParamConditionEntry[]): string {
  if (Array.isArray(cond)) {
    const entries = cond
      .map((c) => `{ param: ${JSON.stringify(c.param)}, equals: ${JSON.stringify(c.equals)} }`)
      .join(", ");
    return `[${entries}]`;
  }
  return `{ param: ${JSON.stringify(cond.param)}, equals: ${JSON.stringify(cond.equals)} }`;
}

// =============================================================================
// Node type generation (catalog.ts)
// =============================================================================

function generateNodeTypeEntry(t: RawNodeType): string {
  const browserCapable = t.platforms.includes("browser");
  return `  ${JSON.stringify(t.name)}: {
    name: ${JSON.stringify(t.name)},
    label: ${JSON.stringify(t.label)},
    description: ${JSON.stringify(t.description)},
    category: ${JSON.stringify(t.category)},
    isContainer: ${t.isContainer},
    browserCapable: ${browserCapable},
    icon: ${JSON.stringify(t.icon)},
  }`;
}

function generateNodeTypesSection(): string {
  const types = catalog.nodeTypes;

  const nodeTypesEntries = types
    .map((t) => `  ${toCamelCase(t.name)}: ${JSON.stringify(t.name)}`)
    .join(",\n");

  const nodeTypeInfoEntries = types.map((t) => generateNodeTypeEntry(t)).join(",\n");

  const categories = [...new Set(types.map((t) => t.category))].sort();
  const categoryUnion = categories.map((c) => `"${c}"`).join(" | ");

  return `// =============================================================================
// Node Types — All ${types.length} registered node types
// =============================================================================

/**
 * All registered node type names.
 * Maps camelCase keys to kebab-case type name strings.
 */
export const NODE_TYPES = {
${nodeTypesEntries},
} as const;

/** Union of all valid node type name strings. */
export type NodeTypeName = (typeof NODE_TYPES)[keyof typeof NODE_TYPES];

/** All node type names as a readonly array. */
export const NODE_TYPE_NAMES: readonly NodeTypeName[] = Object.values(NODE_TYPES) as NodeTypeName[];

/** Node category for grouping in the UI and documentation. */
export type NodeCategory = ${categoryUnion};

/** Metadata describing a node type's behavior and capabilities. */
export interface NodeTypeInfo {
  /** The node type name as used in \`.bnto.json\` definitions. */
  name: NodeTypeName;
  /** Human-readable display label. */
  label: string;
  /** One-sentence description of what the node does. */
  description: string;
  /** Category for grouping. */
  category: NodeCategory;
  /** Whether this node can contain child nodes (group, loop). */
  isContainer: boolean;
  /** Whether this node type is available for browser execution. */
  browserCapable: boolean;
  /** Lucide icon name for visual consumers. */
  icon: string;
}

/**
 * Metadata for all ${types.length} registered node types.
 * Maps node type name → info.
 */
export const NODE_TYPE_INFO: Record<NodeTypeName, NodeTypeInfo> = {
${nodeTypeInfoEntries},
} as const satisfies Record<NodeTypeName, NodeTypeInfo>;`;
}

// =============================================================================
// Processor generation (catalog.ts)
// =============================================================================

function generateParam(p: RawParameter): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  name: ${JSON.stringify(p.name)},`);
  lines.push(`  label: ${JSON.stringify(p.label)},`);
  lines.push(`  description: ${JSON.stringify(p.description)},`);

  if (p.paramType.options) {
    lines.push(`  type: "enum" as const,`);
    lines.push(`  options: ${JSON.stringify(p.paramType.options)} as const,`);
  } else {
    lines.push(`  type: ${JSON.stringify(p.paramType.type)} as const,`);
  }

  if (p.default !== undefined) {
    lines.push(`  default: ${serializeValue(p.default)},`);
  }
  if (p.constraints) {
    const parts: string[] = [];
    if (p.constraints.min !== undefined) parts.push(`min: ${p.constraints.min}`);
    if (p.constraints.max !== undefined) parts.push(`max: ${p.constraints.max}`);
    if (p.constraints.required !== undefined) parts.push(`required: ${p.constraints.required}`);
    lines.push(`  constraints: { ${parts.join(", ")} },`);
  }
  if (p.placeholder !== undefined) {
    lines.push(`  placeholder: ${JSON.stringify(p.placeholder)},`);
  }
  if (p.hidden !== undefined) {
    lines.push(`  hidden: ${p.hidden},`);
  }
  if (p.visibleWhen !== undefined) {
    lines.push(`  visibleWhen: ${serializeCondition(p.visibleWhen)},`);
  }
  if (p.requiredWhen !== undefined) {
    lines.push(`  requiredWhen: ${serializeCondition(p.requiredWhen)},`);
  }
  // surfaceable defaults to true — only emit when false to keep output compact
  if (p.surfaceable === false) {
    lines.push(`  surfaceable: false,`);
  }
  lines.push("}");
  return lines.join("\n");
}

function generateProcessor(p: RawProcessor): string {
  const params = p.parameters.map((param) => indent(generateParam(param), 2)).join(",\n");
  return `{
  nodeType: ${JSON.stringify(p.nodeType)},
  operation: ${JSON.stringify(p.operation)},
  name: ${JSON.stringify(p.name)},
  description: ${JSON.stringify(p.description)},
  category: ${JSON.stringify(p.category)},
  accepts: ${JSON.stringify(p.accepts)} as const,
  platforms: ${JSON.stringify(p.platforms)} as const,
  parameters: [
${params},
  ],
}`;
}

function generateProcessorsSection(): string {
  const sorted = [...catalog.processors].sort((a, b) => {
    const ka = `${a.nodeType}:${a.operation}`;
    const kb = `${b.nodeType}:${b.operation}`;
    return ka.localeCompare(kb);
  });

  const processorsCode = sorted.map((p) => indent(generateProcessor(p), 1)).join(",\n");

  return `// =============================================================================
// Processors — ${sorted.length} implemented operations
// =============================================================================

/** Condition for visibleWhen/requiredWhen rules — single or OR array. */
export type ParamCondition =
  | { readonly param: string; readonly equals: string }
  | ReadonlyArray<{ readonly param: string; readonly equals: string }>;

export type ParamType = "number" | "string" | "boolean" | "enum" | "object";

export interface ProcessorParam {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly type: ParamType;
  readonly options?: readonly string[];
  readonly default?: unknown;
  readonly constraints?: {
    readonly min?: number;
    readonly max?: number;
    readonly required?: boolean;
  };
  readonly placeholder?: string;
  readonly hidden?: boolean;
  readonly visibleWhen?: ParamCondition;
  readonly requiredWhen?: ParamCondition;
  /** Whether this param is eligible for surfacing in container config panels. Defaults to true. */
  readonly surfaceable?: boolean;
}

export interface ProcessorDef {
  readonly nodeType: string;
  readonly operation: string;
  readonly name: string;
  readonly description: string;
  readonly category: string;
  readonly accepts: readonly string[];
  readonly platforms: readonly string[];
  readonly parameters: readonly ProcessorParam[];
}

export const PROCESSORS: readonly ProcessorDef[] = [
${processorsCode},
] as const;

// --- Lookup helpers ---

/** Map keyed by "nodeType:operation" for O(1) lookup. */
export const PROCESSOR_MAP = new Map<string, ProcessorDef>(
  PROCESSORS.map((p) => [\`\${p.nodeType}:\${p.operation}\`, p]),
);

/** Get the engine defaults for a specific processor. */
export function getProcessorDefaults(
  nodeType: string,
  operation: string,
): Record<string, unknown> {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return {};
  const defaults: Record<string, unknown> = {};
  for (const param of proc.parameters) {
    if (param.default !== undefined) {
      defaults[param.name] = param.default;
    }
  }
  return defaults;
}

/** Get the engine constraints for a specific parameter. */
export function getParamConstraints(
  nodeType: string,
  operation: string,
  paramName: string,
): ProcessorParam["constraints"] | undefined {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return undefined;
  const param = proc.parameters.find((p) => p.name === paramName);
  return param?.constraints;
}

/** Get the accepted MIME types for a specific processor. */
export function getProcessorAccepts(
  nodeType: string,
  operation: string,
): readonly string[] {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  return proc?.accepts ?? [];
}`;
}

// =============================================================================
// Zod schema generation (schemas.ts)
// =============================================================================

/**
 * Group processors by nodeType and merge their parameters into a single
 * Zod schema per node type. Also derive the operations enum from processors.
 */
function generateSchemasFile(): string {
  // Group processors by nodeType
  const byNodeType = new Map<string, RawProcessor[]>();
  for (const p of catalog.processors) {
    const existing = byNodeType.get(p.nodeType) ?? [];
    existing.push(p);
    byNodeType.set(p.nodeType, existing);
  }

  const sections: string[] = [];

  // Sort by node type for deterministic output
  const sortedNodeTypes = [...byNodeType.keys()].sort();

  for (const nodeType of sortedNodeTypes) {
    const processors = byNodeType.get(nodeType)!;
    const pascalName = toPascalCase(nodeType);

    // Derive operations list from processors
    const operations = processors.map((p) => p.operation).sort();

    // Merge all parameters from all processors, deduplicating by name
    // If the same param appears in multiple processors, take the first one
    const paramMap = new Map<string, RawParameter>();
    for (const proc of processors) {
      for (const param of proc.parameters) {
        if (!paramMap.has(param.name)) {
          paramMap.set(param.name, param);
        }
      }
    }

    // Build the operation enum constant
    const opsConst = `${nodeType.toUpperCase().replace(/-/g, "_")}_OPERATIONS`;
    sections.push(
      `/** Valid ${nodeType} operations — derived from engine processors. */`,
      `export const ${opsConst} = ${JSON.stringify(operations)} as const;`,
      "",
    );

    // Build per-type Zod schema
    const zodFields: string[] = [];
    zodFields.push(`  operation: z.enum(${opsConst} as unknown as [string, ...string[]]),`);

    for (const [, param] of paramMap) {
      zodFields.push(`  ${generateZodField(param)},`);
    }

    const schemaName = `${toCamelCase(nodeType)}ParamsSchema`;
    const typeName = `${pascalName}Params`;

    sections.push(
      `/** Zod schema for ${nodeType} node parameters (auto-generated from engine). */`,
      `export const ${schemaName} = z.object({`,
      ...zodFields,
      `});`,
      "",
      `/** Inferred TypeScript type for ${nodeType} node parameters. */`,
      `export type ${typeName} = z.infer<typeof ${schemaName}>;`,
      "",
    );

    // Build NodeSchemaDefinition with UI metadata from engine
    const uiMetaEntries: string[] = [];
    uiMetaEntries.push(
      `    operation: {`,
      `      label: "Operation",`,
      `      description: "The ${nodeType} operation to perform.",`,
      `    },`,
    );

    for (const [, param] of paramMap) {
      uiMetaEntries.push(generateNodeParamMeta(param));
    }

    const nodeSchemaName = `${toCamelCase(nodeType)}NodeSchema`;
    sections.push(
      `/** Full schema definition for the ${nodeType} node type (auto-generated from engine). */`,
      `export const ${nodeSchemaName}: NodeSchemaDefinition = {`,
      `  nodeType: ${JSON.stringify(nodeType)},`,
      `  schemaVersion: 1,`,
      `  schema: ${schemaName},`,
      `  params: {`,
      ...uiMetaEntries,
      `  },`,
      `};`,
      "",
    );
  }

  return `/**
 * AUTO-GENERATED from engine/catalog.snapshot.json — DO NOT EDIT.
 *
 * Zod schemas and UI metadata for engine-backed node types.
 * Run \`task nodes:generate\` to regenerate after engine changes.
 *
 * Engine catalog v${catalog.version}
 */

import { z } from "zod";
import type { NodeSchemaDefinition } from "../schemas/types";

${sections.join("\n")}`;
}

/** Generate a single Zod field from a RawParameter. */
function generateZodField(param: RawParameter): string {
  const name = param.name;
  let zodChain: string;

  switch (param.paramType.type) {
    case "number": {
      zodChain = "z.number()";
      if (param.constraints?.min !== undefined) {
        zodChain += `.min(${param.constraints.min})`;
      }
      if (param.constraints?.max !== undefined) {
        zodChain += `.max(${param.constraints.max})`;
      }
      break;
    }
    case "string": {
      zodChain = "z.string()";
      break;
    }
    case "boolean": {
      zodChain = "z.boolean()";
      break;
    }
    case "enum": {
      const options = param.paramType.options ?? [];
      zodChain = `z.enum(${JSON.stringify(options)} as const)`;
      break;
    }
    case "object": {
      zodChain = "z.record(z.string())";
      break;
    }
    default: {
      zodChain = "z.unknown()";
    }
  }

  // Add optional + default.
  // When a param has visibleWhen, it's only relevant for one operation —
  // at the merged node-type schema level it must be optional even if the
  // processor marks it required (the requiredWhen handles conditional req).
  const isConditional = param.visibleWhen !== undefined;
  if (param.constraints?.required && !isConditional) {
    // Truly required across all operations — no .optional()
    if (param.default !== undefined) {
      zodChain += `.default(${serializeValue(param.default)})`;
    }
  } else {
    zodChain += ".optional()";
    if (param.default !== undefined) {
      zodChain += `.default(${serializeValue(param.default)})`;
    }
  }

  return `  ${name}: ${zodChain}`;
}

/** Generate NodeParamMeta entry for a parameter. */
function generateNodeParamMeta(param: RawParameter): string {
  const lines: string[] = [];
  lines.push(`    ${param.name}: {`);
  lines.push(`      label: ${JSON.stringify(param.label)},`);
  lines.push(`      description: ${JSON.stringify(param.description)},`);
  if (param.placeholder !== undefined) {
    lines.push(`      placeholder: ${JSON.stringify(param.placeholder)},`);
  }
  // hidden is a UI concern — lives in FieldConfig, not NodeParamMeta
  if (param.visibleWhen !== undefined) {
    lines.push(`      visibleWhen: ${serializeCondition(param.visibleWhen)},`);
  }
  if (param.requiredWhen !== undefined) {
    lines.push(`      requiredWhen: ${serializeCondition(param.requiredWhen)},`);
  }
  // surfaceable defaults to true — only emit when false
  if (param.surfaceable === false) {
    lines.push(`      surfaceable: false,`);
  }
  lines.push(`    },`);
  return lines.join("\n");
}

// =============================================================================
// Definition JSON Schema generation (definitionSchema.ts)
// =============================================================================

function generateDefinitionSchemaFile(): string {
  if (!catalog.definitionSchema) {
    return `/**
 * Definition JSON Schema — NOT AVAILABLE (engine did not include it).
 */
export const DEFINITION_JSON_SCHEMA = null;
`;
  }

  return `/**
 * AUTO-GENERATED from engine/catalog.snapshot.json — DO NOT EDIT.
 *
 * JSON Schema (Draft 2020-12) for \`.bnto.json\` definition files.
 * Use this to validate definition files in any language or tool
 * that supports JSON Schema (VS Code, ajv, jsonschema, etc.).
 *
 * Run \`task nodes:generate\` to regenerate after engine changes.
 *
 * Engine catalog v${catalog.version}
 */

/** JSON Schema for .bnto.json definition files. */
export const DEFINITION_JSON_SCHEMA = ${JSON.stringify(catalog.definitionSchema, null, 2)} as const;
`;
}

// =============================================================================
// Node README generation (docs/*.md)
// =============================================================================

function formatConstraints(p: RawParameter): string {
  const parts: string[] = [];
  if (p.constraints?.min !== undefined) parts.push(`min: ${p.constraints.min}`);
  if (p.constraints?.max !== undefined) parts.push(`max: ${p.constraints.max}`);
  if (parts.length === 0) return "—";
  return parts.join(", ");
}

function formatRange(p: RawParameter): string {
  if (p.constraints?.min !== undefined && p.constraints?.max !== undefined) {
    return `${p.constraints.min}–${p.constraints.max}`;
  }
  if (p.constraints?.min !== undefined) return `≥ ${p.constraints.min}`;
  if (p.constraints?.max !== undefined) return `≤ ${p.constraints.max}`;
  return "—";
}

function formatVisibleWhen(p: RawParameter): string {
  if (!p.visibleWhen) return "always";
  const conds = Array.isArray(p.visibleWhen) ? p.visibleWhen : [p.visibleWhen];
  if (conds.length === 1) return conds[0].equals;
  return conds.map((c) => c.equals).join(", ");
}

function formatDefault(p: RawParameter): string {
  if (p.default === undefined) return "—";
  return String(p.default);
}

function generateNodeReadme(nodeType: RawNodeType, processors: RawProcessor[]): string {
  const lines: string[] = [];
  const browserCapable = nodeType.platforms.includes("browser");
  const platforms = nodeType.platforms.join(", ") || "none";

  lines.push(`# ${nodeType.label} Node`);
  lines.push("");
  lines.push(`> ${nodeType.description}`);
  lines.push("");
  lines.push(
    `**Category:** ${nodeType.category} | **Platforms:** ${platforms} | **Container:** ${nodeType.isContainer ? "yes" : "no"}`,
  );
  lines.push("");

  // Operations section (multi-operation nodes only)
  if (processors.length > 0) {
    const allAccepts = [...new Set(processors.flatMap((p) => p.accepts))].sort();

    if (allAccepts.length > 0) {
      lines.push("## Accepts");
      lines.push("");
      for (const mime of allAccepts) {
        lines.push(`- \`${mime}\``);
      }
      lines.push("");
    }

    lines.push("## Operations");
    lines.push("");
    for (const proc of processors) {
      lines.push(`### ${proc.operation}`);
      lines.push("");
      lines.push(proc.description);
      if (proc.accepts.length > 0) {
        lines.push("");
        lines.push(`Accepts: ${proc.accepts.map((a) => `\`${a}\``).join(", ")}`);
      }
      lines.push("");
    }

    // Merged parameter table
    const paramMap = new Map<string, RawParameter>();
    for (const proc of processors) {
      for (const param of proc.parameters) {
        if (!paramMap.has(param.name)) {
          paramMap.set(param.name, param);
        }
      }
    }

    if (paramMap.size > 0) {
      lines.push("## Parameters");
      lines.push("");
      lines.push("| Parameter | Type | Default | Range | Visible When | Description |");
      lines.push("|-----------|------|---------|-------|--------------|-------------|");

      // Operation param first (synthetic)
      const operations = processors.map((p) => p.operation).sort();
      lines.push(
        `| operation | enum | — | ${operations.join(", ")} | always | Processing operation |`,
      );

      for (const [, param] of paramMap) {
        const type = param.paramType.options ? "enum" : param.paramType.type;
        const range = param.paramType.options
          ? param.paramType.options.join(", ")
          : formatRange(param);
        lines.push(
          `| ${param.name} | ${type} | ${formatDefault(param)} | ${range} | ${formatVisibleWhen(param)} | ${param.description} |`,
        );
      }
      lines.push("");
    }
  }

  // Configuration example
  if (processors.length > 0) {
    const firstProc = processors[0];
    const exampleParams: Record<string, unknown> = { operation: firstProc.operation };
    for (const param of firstProc.parameters) {
      if (param.default !== undefined) {
        exampleParams[param.name] = param.default;
      } else if (param.constraints?.required) {
        exampleParams[param.name] = param.paramType.options?.[0] ?? `<${param.paramType.type}>`;
      }
    }

    lines.push("## Configuration Example");
    lines.push("");
    lines.push("```json");
    lines.push(`{`);
    lines.push(`  "type": ${JSON.stringify(nodeType.name)},`);
    lines.push(
      `  "parameters": ${JSON.stringify(exampleParams, null, 4)
        .split("\n")
        .map((l, i) => (i === 0 ? l : "  " + l))
        .join("\n")}`,
    );
    lines.push(`}`);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `*Auto-generated from engine catalog v${catalog.version}. Run \`task nodes:generate\` to regenerate.*`,
  );
  lines.push("");

  return lines.join("\n");
}

function generateAllNodeReadmes(): void {
  mkdirSync(DOCS_DIR, { recursive: true });

  const processorsByType = new Map<string, RawProcessor[]>();
  for (const p of catalog.processors) {
    const existing = processorsByType.get(p.nodeType) ?? [];
    existing.push(p);
    processorsByType.set(p.nodeType, existing);
  }

  for (const nodeType of catalog.nodeTypes) {
    const processors = processorsByType.get(nodeType.name) ?? [];
    const readme = generateNodeReadme(nodeType, processors);
    const filename = resolve(DOCS_DIR, `${nodeType.name}.md`);
    writeFileSync(filename, readme, "utf-8");
  }

  console.log(`Generated ${catalog.nodeTypes.length} node READMEs in ${DOCS_DIR}`);
}

// =============================================================================
// Assemble and write
// =============================================================================

const catalogOutput = `/**
 * AUTO-GENERATED from engine/catalog.snapshot.json — DO NOT EDIT.
 *
 * Run \`task nodes:generate\` to regenerate after engine changes.
 * Source: engine/crates/bnto-core/src/metadata.rs
 *
 * The Rust engine is the single source of truth for all node metadata.
 * To add or modify a node type, edit \`all_node_types()\` in the engine,
 * then run \`task wasm:build\` → \`task nodes:generate\`.
 *
 * Engine catalog v${catalog.version}
 */

${generateNodeTypesSection()}

${generateProcessorsSection()}
`;

const schemasOutput = generateSchemasFile();
const defSchemaOutput = generateDefinitionSchemaFile();

mkdirSync(GENERATED_DIR, { recursive: true });
writeFileSync(CATALOG_OUTPUT, catalogOutput, "utf-8");
writeFileSync(SCHEMAS_OUTPUT, schemasOutput, "utf-8");
writeFileSync(DEF_SCHEMA_OUTPUT, defSchemaOutput, "utf-8");
generateAllNodeReadmes();

// Clean up old separate file
try {
  rmSync(OLD_NODE_TYPES);
  console.log(`Removed stale ${OLD_NODE_TYPES}`);
} catch {
  // Doesn't exist, that's fine
}

console.log(`Generated ${CATALOG_OUTPUT}`);
console.log(
  `  ${catalog.nodeTypes.length} node types + ${catalog.processors.length} processors from engine catalog v${catalog.version}`,
);
console.log(`Generated ${SCHEMAS_OUTPUT}`);
console.log(
  `  Zod schemas for ${new Set(catalog.processors.map((p) => p.nodeType)).size} engine-backed node types`,
);
console.log(`Generated ${DEF_SCHEMA_OUTPUT}`);
console.log(
  `  Definition JSON Schema ${catalog.definitionSchema ? "included" : "NOT included (engine didn't provide it)"}`,
);
