/**
 * Codegen: engine catalog → TypeScript module.
 *
 * Reads `engine/catalog.snapshot.json` (generated by the Rust engine)
 * and produces `src/generated/catalog.ts` — the single generated module
 * containing both node type definitions and processor metadata.
 *
 * The Rust engine is the single source of truth for ALL node metadata.
 * Run via: `task nodes:generate` or `npx tsx scripts/generate-from-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";

// --- Paths ---

const ROOT = resolve(dirname(import.meta.url.replace("file://", "")), "../../../..");
const CATALOG_PATH = resolve(ROOT, "engine/catalog.snapshot.json");
const GENERATED_DIR = resolve(ROOT, "packages/@bnto/nodes/src/generated");
const OUTPUT_PATH = resolve(GENERATED_DIR, "catalog.ts");

// Clean up old separate nodeTypes.ts if it exists
const OLD_NODE_TYPES = resolve(GENERATED_DIR, "nodeTypes.ts");

// --- Types matching engine/catalog.snapshot.json schema ---

interface CatalogEnvelope {
  version: string;
  nodeTypes: RawNodeType[];
  processors: RawProcessor[];
}

interface RawNodeType {
  name: string;
  label: string;
  description: string;
  category: string;
  isContainer: boolean;
  platforms: string[];
  icon: string;
}

interface RawProcessor {
  nodeType: string;
  operation: string;
  name: string;
  description: string;
  category: string;
  accepts: string[];
  platforms: string[];
  parameters: RawParameter[];
}

interface RawParameter {
  name: string;
  label: string;
  description: string;
  paramType: { type: string; options?: string[] };
  default?: unknown;
  constraints?: { min?: number; max?: number; required?: boolean };
}

// --- Read catalog ---

const raw = readFileSync(CATALOG_PATH, "utf-8");
const catalog: CatalogEnvelope = JSON.parse(raw);

// --- Helpers ---

function indent(s: string, n: number): string {
  const pad = "  ".repeat(n);
  return s
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}

function serializeValue(v: unknown): string {
  if (v === null || v === undefined) return "undefined";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}

/** Convert kebab-case to camelCase. */
function toCamelCase(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// =============================================================================
// Node type generation
// =============================================================================

function generateNodeTypeEntry(t: RawNodeType): string {
  const browserCapable = t.platforms.includes("browser");
  return `  ${JSON.stringify(t.name)}: {
    name: ${JSON.stringify(t.name)},
    label: ${JSON.stringify(t.label)},
    description: ${JSON.stringify(t.description)},
    category: ${JSON.stringify(t.category)},
    isContainer: ${t.isContainer},
    browserCapable: ${browserCapable},
    icon: ${JSON.stringify(t.icon)},
  }`;
}

function generateNodeTypesSection(): string {
  const types = catalog.nodeTypes;

  const nodeTypesEntries = types
    .map((t) => `  ${toCamelCase(t.name)}: ${JSON.stringify(t.name)}`)
    .join(",\n");

  const nodeTypeInfoEntries = types.map((t) => generateNodeTypeEntry(t)).join(",\n");

  const categories = [...new Set(types.map((t) => t.category))].sort();
  const categoryUnion = categories.map((c) => `"${c}"`).join(" | ");

  return `// =============================================================================
// Node Types — All ${types.length} registered node types
// =============================================================================

/**
 * All registered node type names.
 * Maps camelCase keys to kebab-case type name strings.
 */
export const NODE_TYPES = {
${nodeTypesEntries},
} as const;

/** Union of all valid node type name strings. */
export type NodeTypeName = (typeof NODE_TYPES)[keyof typeof NODE_TYPES];

/** All node type names as a readonly array. */
export const NODE_TYPE_NAMES: readonly NodeTypeName[] = Object.values(NODE_TYPES) as NodeTypeName[];

/** Node category for grouping in the UI and documentation. */
export type NodeCategory = ${categoryUnion};

/** Metadata describing a node type's behavior and capabilities. */
export interface NodeTypeInfo {
  /** The node type name as used in \`.bnto.json\` definitions. */
  name: NodeTypeName;
  /** Human-readable display label. */
  label: string;
  /** One-sentence description of what the node does. */
  description: string;
  /** Category for grouping. */
  category: NodeCategory;
  /** Whether this node can contain child nodes (group, loop). */
  isContainer: boolean;
  /** Whether this node type is available for browser execution. */
  browserCapable: boolean;
  /** Lucide icon name for visual consumers. */
  icon: string;
}

/**
 * Metadata for all ${types.length} registered node types.
 * Maps node type name → info.
 */
export const NODE_TYPE_INFO: Record<NodeTypeName, NodeTypeInfo> = {
${nodeTypeInfoEntries},
} as const satisfies Record<NodeTypeName, NodeTypeInfo>;`;
}

// =============================================================================
// Processor generation
// =============================================================================

function generateParam(p: RawParameter): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  name: ${JSON.stringify(p.name)},`);
  lines.push(`  label: ${JSON.stringify(p.label)},`);
  lines.push(`  description: ${JSON.stringify(p.description)},`);

  if (p.paramType.options) {
    lines.push(`  type: "enum" as const,`);
    lines.push(`  options: ${JSON.stringify(p.paramType.options)} as const,`);
  } else {
    lines.push(`  type: ${JSON.stringify(p.paramType.type)} as const,`);
  }

  if (p.default !== undefined) {
    lines.push(`  default: ${serializeValue(p.default)},`);
  }
  if (p.constraints) {
    const parts: string[] = [];
    if (p.constraints.min !== undefined) parts.push(`min: ${p.constraints.min}`);
    if (p.constraints.max !== undefined) parts.push(`max: ${p.constraints.max}`);
    if (p.constraints.required !== undefined) parts.push(`required: ${p.constraints.required}`);
    lines.push(`  constraints: { ${parts.join(", ")} },`);
  }
  lines.push("}");
  return lines.join("\n");
}

function generateProcessor(p: RawProcessor): string {
  const params = p.parameters.map((param) => indent(generateParam(param), 2)).join(",\n");
  return `{
  nodeType: ${JSON.stringify(p.nodeType)},
  operation: ${JSON.stringify(p.operation)},
  name: ${JSON.stringify(p.name)},
  description: ${JSON.stringify(p.description)},
  category: ${JSON.stringify(p.category)},
  accepts: ${JSON.stringify(p.accepts)} as const,
  platforms: ${JSON.stringify(p.platforms)} as const,
  parameters: [
${params},
  ],
}`;
}

function generateProcessorsSection(): string {
  const sorted = [...catalog.processors].sort((a, b) => {
    const ka = `${a.nodeType}:${a.operation}`;
    const kb = `${b.nodeType}:${b.operation}`;
    return ka.localeCompare(kb);
  });

  const processorsCode = sorted.map((p) => indent(generateProcessor(p), 1)).join(",\n");

  return `// =============================================================================
// Processors — ${sorted.length} implemented operations
// =============================================================================

export type ParamType = "number" | "string" | "boolean" | "enum" | "object";

export interface ProcessorParam {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly type: ParamType;
  readonly options?: readonly string[];
  readonly default?: unknown;
  readonly constraints?: {
    readonly min?: number;
    readonly max?: number;
    readonly required?: boolean;
  };
}

export interface ProcessorDef {
  readonly nodeType: string;
  readonly operation: string;
  readonly name: string;
  readonly description: string;
  readonly category: string;
  readonly accepts: readonly string[];
  readonly platforms: readonly string[];
  readonly parameters: readonly ProcessorParam[];
}

export const PROCESSORS: readonly ProcessorDef[] = [
${processorsCode},
] as const;

// --- Lookup helpers ---

/** Map keyed by "nodeType:operation" for O(1) lookup. */
export const PROCESSOR_MAP = new Map<string, ProcessorDef>(
  PROCESSORS.map((p) => [\`\${p.nodeType}:\${p.operation}\`, p]),
);

/** Get the engine defaults for a specific processor. */
export function getProcessorDefaults(
  nodeType: string,
  operation: string,
): Record<string, unknown> {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return {};
  const defaults: Record<string, unknown> = {};
  for (const param of proc.parameters) {
    if (param.default !== undefined) {
      defaults[param.name] = param.default;
    }
  }
  return defaults;
}

/** Get the engine constraints for a specific parameter. */
export function getParamConstraints(
  nodeType: string,
  operation: string,
  paramName: string,
): ProcessorParam["constraints"] | undefined {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return undefined;
  const param = proc.parameters.find((p) => p.name === paramName);
  return param?.constraints;
}

/** Get the accepted MIME types for a specific processor. */
export function getProcessorAccepts(
  nodeType: string,
  operation: string,
): readonly string[] {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  return proc?.accepts ?? [];
}`;
}

// =============================================================================
// Assemble and write
// =============================================================================

const output = `/**
 * AUTO-GENERATED from engine/catalog.snapshot.json — DO NOT EDIT.
 *
 * Run \`task nodes:generate\` to regenerate after engine changes.
 * Source: engine/crates/bnto-core/src/metadata.rs
 *
 * The Rust engine is the single source of truth for all node metadata.
 * To add or modify a node type, edit \`all_node_types()\` in the engine,
 * then run \`task wasm:build\` → \`task nodes:generate\`.
 *
 * Engine catalog v${catalog.version}
 */

${generateNodeTypesSection()}

${generateProcessorsSection()}
`;

mkdirSync(GENERATED_DIR, { recursive: true });
writeFileSync(OUTPUT_PATH, output, "utf-8");

// Clean up old separate file
try {
  rmSync(OLD_NODE_TYPES);
  console.log(`Removed stale ${OLD_NODE_TYPES}`);
} catch {
  // Doesn't exist, that's fine
}

console.log(`Generated ${OUTPUT_PATH}`);
console.log(
  `  ${catalog.nodeTypes.length} node types + ${catalog.processors.length} processors from engine catalog v${catalog.version}`,
);
