/**
 * Codegen: engine catalog → TypeScript module.
 *
 * Reads `engine/catalog.snapshot.json` (generated by the Rust engine)
 * and produces `packages/@bnto/nodes/src/generated/catalog.ts` — typed
 * processor definitions with defaults, constraints, and accepted MIME
 * types. This makes the Rust engine the single source of truth for
 * node metadata.
 *
 * Run via: `task nodes:generate` or `npx tsx scripts/generate-from-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

// --- Paths ---

const ROOT = resolve(dirname(import.meta.url.replace("file://", "")), "../../../..");
const CATALOG_PATH = resolve(ROOT, "engine/catalog.snapshot.json");
const OUTPUT_PATH = resolve(ROOT, "packages/@bnto/nodes/src/generated/catalog.ts");

// --- Types matching engine/catalog.snapshot.json schema ---

interface CatalogEnvelope {
  version: string;
  processors: RawProcessor[];
}

interface RawProcessor {
  nodeType: string;
  operation: string;
  name: string;
  description: string;
  category: string;
  accepts: string[];
  platforms: string[];
  parameters: RawParameter[];
}

interface RawParameter {
  name: string;
  label: string;
  description: string;
  paramType: { type: string; options?: string[] };
  default?: unknown;
  constraints?: { min?: number; max?: number; required?: boolean };
}

// --- Read catalog ---

const raw = readFileSync(CATALOG_PATH, "utf-8");
const catalog: CatalogEnvelope = JSON.parse(raw);

// --- Generate TypeScript ---

function indent(s: string, n: number): string {
  const pad = "  ".repeat(n);
  return s
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}

function serializeValue(v: unknown): string {
  if (v === null || v === undefined) return "undefined";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}

function generateParam(p: RawParameter): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  name: ${JSON.stringify(p.name)},`);
  lines.push(`  label: ${JSON.stringify(p.label)},`);
  lines.push(`  description: ${JSON.stringify(p.description)},`);

  // paramType
  if (p.paramType.options) {
    lines.push(`  type: "enum" as const,`);
    lines.push(`  options: ${JSON.stringify(p.paramType.options)} as const,`);
  } else {
    lines.push(`  type: ${JSON.stringify(p.paramType.type)} as const,`);
  }

  if (p.default !== undefined) {
    lines.push(`  default: ${serializeValue(p.default)},`);
  }
  if (p.constraints) {
    const parts: string[] = [];
    if (p.constraints.min !== undefined) parts.push(`min: ${p.constraints.min}`);
    if (p.constraints.max !== undefined) parts.push(`max: ${p.constraints.max}`);
    if (p.constraints.required !== undefined) parts.push(`required: ${p.constraints.required}`);
    lines.push(`  constraints: { ${parts.join(", ")} },`);
  }
  lines.push("}");
  return lines.join("\n");
}

function generateProcessor(p: RawProcessor): string {
  const params = p.parameters.map((param) => indent(generateParam(param), 2)).join(",\n");
  return `{
  nodeType: ${JSON.stringify(p.nodeType)},
  operation: ${JSON.stringify(p.operation)},
  name: ${JSON.stringify(p.name)},
  description: ${JSON.stringify(p.description)},
  category: ${JSON.stringify(p.category)},
  accepts: ${JSON.stringify(p.accepts)} as const,
  platforms: ${JSON.stringify(p.platforms)} as const,
  parameters: [
${params},
  ],
}`;
}

// Sort processors by nodeType:operation for deterministic output
const sorted = [...catalog.processors].sort((a, b) => {
  const ka = `${a.nodeType}:${a.operation}`;
  const kb = `${b.nodeType}:${b.operation}`;
  return ka.localeCompare(kb);
});

const processorsCode = sorted.map((p) => indent(generateProcessor(p), 1)).join(",\n");

const output = `/**
 * AUTO-GENERATED from engine/catalog.snapshot.json — DO NOT EDIT.
 *
 * Run \`task nodes:generate\` to regenerate after engine changes.
 * Source: engine/crates/bnto-wasm/src/catalog.rs
 *
 * This module is the TypeScript representation of the Rust engine's
 * self-describing processor metadata. It provides typed definitions,
 * defaults, and constraints for all engine-implemented node operations.
 */

// --- Types ---

export type ParamType = "number" | "string" | "boolean" | "enum" | "object";

export interface ProcessorParam {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly type: ParamType;
  readonly options?: readonly string[];
  readonly default?: unknown;
  readonly constraints?: {
    readonly min?: number;
    readonly max?: number;
    readonly required?: boolean;
  };
}

export interface ProcessorDef {
  readonly nodeType: string;
  readonly operation: string;
  readonly name: string;
  readonly description: string;
  readonly category: string;
  readonly accepts: readonly string[];
  readonly platforms: readonly string[];
  readonly parameters: readonly ProcessorParam[];
}

// --- Processor definitions (from engine catalog v${catalog.version}) ---

export const PROCESSORS: readonly ProcessorDef[] = [
${processorsCode},
] as const;

// --- Lookup helpers ---

/** Map keyed by "nodeType:operation" for O(1) lookup. */
export const PROCESSOR_MAP = new Map<string, ProcessorDef>(
  PROCESSORS.map((p) => [\`\${p.nodeType}:\${p.operation}\`, p]),
);

/**
 * Get the engine defaults for a specific processor.
 *
 * Returns a record of parameter names to their default values,
 * including only parameters that have engine-defined defaults.
 * Recipe-specific overrides (e.g., format: "webp") are NOT included —
 * those are authoring choices, not engine defaults.
 */
export function getProcessorDefaults(
  nodeType: string,
  operation: string,
): Record<string, unknown> {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return {};
  const defaults: Record<string, unknown> = {};
  for (const param of proc.parameters) {
    if (param.default !== undefined) {
      defaults[param.name] = param.default;
    }
  }
  return defaults;
}

/**
 * Get the engine constraints for a specific parameter.
 *
 * Returns { min, max, required } if the engine defines constraints,
 * or undefined if no constraints exist.
 */
export function getParamConstraints(
  nodeType: string,
  operation: string,
  paramName: string,
): ProcessorParam["constraints"] | undefined {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  if (!proc) return undefined;
  const param = proc.parameters.find((p) => p.name === paramName);
  return param?.constraints;
}

/**
 * Get the accepted MIME types for a specific processor.
 */
export function getProcessorAccepts(
  nodeType: string,
  operation: string,
): readonly string[] {
  const proc = PROCESSOR_MAP.get(\`\${nodeType}:\${operation}\`);
  return proc?.accepts ?? [];
}
`;

// --- Write output ---

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, output, "utf-8");

const count = sorted.length;
console.log(`Generated ${OUTPUT_PATH}`);
console.log(`  ${count} processors from engine catalog v${catalog.version}`);
