/**
 * Icon re-exports — single swap point for icon providers.
 *
 * All app code imports icons from here, never from "lucide-react" directly.
 * To switch providers, update the exports in this file only.
 */

export {
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowRightLeft as ArrowRightLeftIcon,
  ArrowUpRight as ArrowUpRightIcon,
  BookOpen as BookOpenIcon,
  Check as CheckIcon,
  CheckCircle2 as CheckCircle2Icon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  CircleMinus as CircleMinusIcon,
  Clock as ClockIcon,
  Columns3 as Columns3Icon,
  Download as DownloadIcon,
  FileArchive as FileArchiveIcon,
  FileAudio as FileAudioIcon,
  FileCode as FileCodeIcon,
  FileCog as FileCogIcon,
  FileDown as FileDownIcon,
  File as FileIcon,
  FileText as FileTextIcon,
  FileVideo as FileVideoIcon,
  Github as GithubIcon,
  Globe as GlobeIcon,
  GripVertical as GripVerticalIcon,
  Heart as HeartIcon,
  Laptop as LaptopIcon,
  Loader2 as LoaderIcon,
  Menu as MenuIcon,
  Minimize2 as Minimize2Icon,
  Moon as MoonIcon,
  PenLine as PenLineIcon,
  Play as PlayIcon,
  RotateCcw as RotateCcwIcon,
  Scaling as ScalingIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkles as SparklesIcon,
  Star as StarIcon,
  Sun as SunIcon,
  Sunset as SunsetIcon,
  Trash2 as TrashIcon,
  Upload as UploadIcon,
  CircleUser as CircleUserIcon,
  LogOut as LogOutIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline as UnderlineIcon,
  Pin as PinIcon,
  X as XIcon,
  XCircle as XCircleIcon,
  Zap as ZapIcon,
} from "lucide-react";

export type { LucideIcon } from "lucide-react";
