/**
 * Icon re-exports — single swap point for icon providers.
 *
 * All app code imports icons from here, never from "lucide-react" directly.
 * To switch providers, update the exports in this file only.
 */

export {
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowRightLeft as ArrowRightLeftIcon,
  ArrowUpRight as ArrowUpRightIcon,
  Blocks as BlocksIcon,
  BookOpen as BookOpenIcon,
  Check as CheckIcon,
  CheckCircle2 as CheckCircle2Icon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  CircleMinus as CircleMinusIcon,
  Clock as ClockIcon,
  Columns3 as Columns3Icon,
  Download as DownloadIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileArchive as FileArchiveIcon,
  FileAudio as FileAudioIcon,
  FileCode as FileCodeIcon,
  FileCog as FileCogIcon,
  FileDown as FileDownIcon,
  File as FileIcon,
  FolderOpen as FolderOpenIcon,
  FileText as FileTextIcon,
  FileVideo as FileVideoIcon,
  Github as GithubIcon,
  Globe as GlobeIcon,
  GripVertical as GripVerticalIcon,
  Heart as HeartIcon,
  History as HistoryIcon,
  Image as ImageIcon,
  Laptop as LaptopIcon,
  Layers as LayersIcon,
  Loader2 as LoaderIcon,
  Menu as MenuIcon,
  Minus as MinusIcon,
  Minimize2 as Minimize2Icon,
  Moon as MoonIcon,
  PanelLeft as PanelLeftIcon,
  PanelLeftClose as PanelLeftCloseIcon,
  PenLine as PenLineIcon,
  Play as PlayIcon,
  RotateCcw as RotateCcwIcon,
  Save as SaveIcon,
  Scaling as ScalingIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkles as SparklesIcon,
  Square as SquareIcon,
  Star as StarIcon,
  Sun as SunIcon,
  Sunset as SunsetIcon,
  Trash2 as TrashIcon,
  Upload as UploadIcon,
  CircleUser as CircleUserIcon,
  LogIn as LogInIcon,
  LogOut as LogOutIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline as UnderlineIcon,
  Plus as PlusIcon,
  Pin as PinIcon,
  Redo2 as Redo2Icon,
  Undo2 as Undo2Icon,
  Copy as CopyIcon,
  EllipsisVertical as EllipsisVerticalIcon,
  Search as SearchIcon,
  X as XIcon,
  XCircle as XCircleIcon,
  Zap as ZapIcon,
} from "lucide-react";

export type { LucideIcon } from "lucide-react";
